pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/praveendama22/JMeter-DemoPublic.git'
            }
        }
        stage('Execute JMeter') {
            steps {
            
                bat """
                C:\\Users\\pdama\\Downloads\\apache-jmeter-5.5\\bin\\jmeter.bat -n -t "TestPlan\\RubricDemo.jmx" -l DemoRun.jtl
                """
            
            }
        }
        stage('Publish Report') {
            steps {
            
                perfReport filterRegex: '', sourceDataFiles: '**/*.jtl'
            
            }
        }
    }
}
